global:
  scrape_interval: 15s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.122.110:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.122.110:8081']


  - job_name: 'telegraf'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.122.110:9273']

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 192.168.122.110:9093

rule_files:
  - "alert.rules"